from pathlib import Path

import httpx
from rich.console import Group
from rich.syntax import Syntax
from rich.table import Table
from rich.text import Text
from textual import work
from textual.app import App, ComposeResult
from textual.containers import Horizontal, Vertical, VerticalScroll
from textual.screen import ModalScreen
from textual.widgets import Button, Footer, Label, RichLog, Select, Static, TabbedContent, TabPane, Tabs, Tab, TextArea

from jev_router_demo.config import Config
from jev_router_demo.inspection import SECTIONS, abbreviate, export_result, inspect_result, section_value
from jev_router_demo.scenarios import SCENARIOS, Scenario
from jev_router_demo.session import DemoSession, safe_display
from jev_router_demo.ui import cumulative_panel, number


class RequestEditor(ModalScreen[str | None]):
    BINDINGS = [("escape", "cancel", "Cancel"), ("ctrl+s", "save", "Save")]

    def __init__(self, request: str):
        super().__init__()
        self.request = request

    def compose(self) -> ComposeResult:
        with Vertical(id="editor-dialog"):
            yield Label("CUSTOM REQUEST · Ctrl+S to save · Esc to cancel")
            yield TextArea(self.request, id="request-editor", soft_wrap=True)
            with Horizontal(classes="toolbar"):
                yield Button("Save request", id="save-request", variant="primary")
                yield Button("Cancel", id="cancel-request")

    def on_mount(self):
        self.query_one(TextArea).focus()

    def action_cancel(self):
        self.dismiss(None)

    def action_save(self):
        value = self.query_one(TextArea).text
        if value.strip():
            self.dismiss(value)
        else:
            self.notify("Request cannot be empty.", severity="warning")

    def on_button_pressed(self, event: Button.Pressed):
        if event.button.id == "save-request":
            self.action_save()
        else:
            self.action_cancel()


def card_content(name, model, state, result):
    color = "cyan" if name == "LLM" else "green"
    heading = Text(f"{name}  /  {model}\n", style=f"bold {color}")
    status = Text({"idle": "READY", "running": "● ROUTING…", "success": "✓ COMPLETE", "error": "✕ ERROR"}[state], style="yellow" if state == "running" else color)
    if not result:
        return Group(heading, status, Text("\nRun a scenario to inspect actual routing decisions.", style="dim"))
    decision = result.decision
    route = Text("\n" + (decision.model_tier.upper() + " MODEL" if decision else "NO ROUTE"), style=f"bold {color}")
    flags = Text("\n")
    if decision:
        flags.append("WEB " + ("ON" if decision.needs_web else "OFF"), style="bold")
        flags.append("   ·   ")
        flags.append("APPROVAL " + ("REQUIRED" if decision.needs_approval else "NOT REQUIRED"), style="bold yellow" if decision.needs_approval else "dim")
    table = Table.grid(padding=(0, 2), expand=True)
    table.add_column(style="dim")
    table.add_column(justify="right")
    for label, value in [("Latency", number(result.latency_ms, " ms")), ("Input / output tokens", f"{number(result.input_tokens)} / {number(result.output_tokens)}"),
                         ("Total tokens", number(result.total_tokens)), ("Generated bytes", number(result.generated_bytes)),
                         ("Decision / parse", result.output_kind + " / " + ("FAILED" if result.parse_success is False else "OK" if result.parse_success else "not required" if not result.parse_required else "unavailable")),
                         ("Parse time", number(result.parse_ms, " ms"))]:
        table.add_row(label, value)
    items = [heading, status, route, flags, Text(""), table]
    if result.error:
        items.append(Text("\n" + safe_display(result.error), style="bold red"))
    if result.probabilities:
        items.append(Text("\nReported candidate probabilities", style="bold"))
        for field, candidates in result.probabilities.items():
            items.append(Text(field + ": " + ", ".join(f"{candidate} {probability:.0%}" for candidate, probability in candidates.items())))
    return Group(*items)


class RouterDemoApp(App):
    CSS_PATH = "tui.tcss"
    TITLE = "JEV / ROUTER LAB"
    BINDINGS = [("r", "run_compare", "Run"), ("n", "next", "Next"), ("p", "previous", "Previous"),
                ("e", "edit", "Edit"), ("o", "inspect", "HTTP inspector"), ("q", "quit", "Quit")]

    def __init__(self, config: Config, client: httpx.AsyncClient | None = None):
        super().__init__()
        self.config = config
        self.client = client or httpx.AsyncClient()
        self.owns_client = client is None
        self.session = DemoSession(config, self.client)
        self.index = 0
        self.scenario = SCENARIOS[0]
        self.full = False
        self.section = "request"
        self.inspector_text = ""

    def compose(self) -> ComposeResult:
        yield Static(Text("JEV / ROUTER LAB   ·   Live decision comparison", style="bold cyan"), id="brand")
        yield Static("ROUTING-ONLY SIMULATION  ·  No downstream execution  ·  Ollama uses generated decisions", id="subtitle")
        with Horizontal(classes="toolbar"):
            yield Select([(f"{i+1:02}  {item.label}", i) for i, item in enumerate(SCENARIOS)] + [("Custom request", -1)], value=0, allow_blank=False, id="scenario")
            yield Button("Run  [r]", variant="primary", id="run")
            yield Button("Edit  [e]", id="edit")
        yield Static(id="request-preview")
        with TabbedContent(id="views"):
            with TabPane("Comparison", id="comparison"):
                with VerticalScroll():
                    with Horizontal(id="cards"):
                        yield Static(id="card-LLM", classes="result-card llm")
                        yield Static(id="card-JEV", classes="result-card jev")
                    yield Static(id="comparison-summary")
                    yield Static("Observed values only. Model, cache and cold-load differences affect this comparison.\n'-' means unavailable, not zero. Expected routes are scenario metadata only.", classes="note")
            with TabPane("HTTP inspector", id="inspector"):
                with Horizontal(classes="toolbar"):
                    yield Select([("LLM", "LLM"), ("Jev", "JEV")], value="LLM", allow_blank=False, id="router")
                    yield Button("Show full", id="full-toggle")
                    yield Button("Export original", id="export")
                yield Static(id="http-meta")
                yield Tabs(*(Tab(label, id=key) for key, label in SECTIONS.items()), id="sections")
                yield Static(id="preview-label", classes="note")
                yield RichLog(id="json-log", wrap=False, auto_scroll=False, min_width=0)
            with TabPane("Session metrics", id="metrics"):
                with VerticalScroll():
                    yield Static(id="metrics-table")
        yield Static("Choose a scenario, then press r. Commands do not need Enter.", id="status")
        yield Footer()

    def on_mount(self):
        self.set_class(self.size.width < 100, "compact")
        self.query_one("#cards").set_class(self.size.width < 100, "narrow")
        self.refresh_request()
        self.refresh_results()

    def on_resize(self, event):
        if self.is_mounted and self.query("#cards"):
            self.query_one("#cards").set_class(event.size.width < 100, "narrow")
            self.set_class(event.size.width < 100, "compact")

    def refresh_request(self):
        preview, count = abbreviate(self.scenario.request)
        text = Text(self.scenario.label + "\n", style="bold")
        text.append(safe_display(preview))
        if count:
            text.append("\n요약 표시 · 원본 변경 없음", style="dim")
        self.query_one("#request-preview", Static).update(text)

    def refresh_results(self):
        for name in self.session.routers:
            self.query_one(f"#card-{name}", Static).update(card_content(name, self.session.models[name], self.session.states[name], self.session.results.get(name)))
        comparison = self.session.snapshot()["comparison"]
        ratio = comparison["latency_ratio"]
        delta = comparison["output_token_difference"]
        self.query_one("#comparison-summary", Static).update(Text(
            f"OBSERVED COMPARISON   ·   Latency LLM / Jev: {number(ratio)}×   ·   Output tokens LLM − Jev: {number(delta)}", style="bold"))
        self.query_one("#metrics-table", Static).update(cumulative_panel(self.session.metrics))
        self.refresh_inspector()

    def refresh_inspector(self):
        name = self.query_one("#router", Select).value
        result = self.session.results.get(name)
        log = self.query_one("#json-log", RichLog)
        log.clear()
        if not result:
            self.inspector_text = "Run this router to inspect its HTTP exchange."
            self.query_one("#http-meta", Static).update(f"{name} · {self.session.states.get(name, 'idle')}")
            self.query_one("#preview-label", Static).update("Waiting for a result.")
            log.write(self.inspector_text)
            return
        value, is_json = section_value(result, self.section)
        _, count = abbreviate(value)
        self.inspector_text = safe_display(inspect_result(result, self.section, full=self.full))
        exchange = result.http
        self.query_one("#http-meta", Static).update(Text(f"{exchange.method} {exchange.url} · HTTP {exchange.status_code or 'no response'}") if exchange else Text(name))
        self.query_one("#preview-label", Static).update("전체 보기 · Export always saves original" if self.full else f"요약 표시 · {count}개 중략 · 원본 변경 없음")
        log.write(Syntax(self.inspector_text, "json" if is_json else "text", theme="monokai", line_numbers=True, word_wrap=False))

    def on_select_changed(self, event: Select.Changed):
        if event.select.id == "scenario" and not self.session.running:
            if event.value != -1:
                self.index = int(event.value)
                self.scenario = SCENARIOS[self.index]
                self.session.results.clear()
                self.session.states = dict.fromkeys(self.session.routers, "idle")
                self.refresh_request()
                self.refresh_results()
        elif event.select.id == "router":
            self.refresh_inspector()

    def on_tabs_tab_activated(self, event: Tabs.TabActivated):
        if event.tabs.id == "sections":
            self.section = event.tab.id
            self.refresh_inspector()

    def on_button_pressed(self, event: Button.Pressed):
        actions = {"run": self.action_run_compare, "edit": self.action_edit, "full-toggle": self.toggle_full, "export": self.export_original}
        if event.button.id in actions:
            actions[event.button.id]()

    def toggle_full(self):
        self.full = not self.full
        self.query_one("#full-toggle", Button).label = "Show summary" if self.full else "Show full"
        self.refresh_inspector()

    def export_original(self):
        result = self.session.results.get(self.query_one("#router", Select).value)
        if result:
            try:
                path = export_result(result, self.section, Path.cwd() / "exports")
                self.notify(f"Original saved: {path}", timeout=8)
            except OSError as exc:
                self.notify(f"Cannot export: {exc}", severity="error")
        else:
            self.notify("Run a request first.", severity="warning")

    def action_next(self):
        if not self.session.running and not isinstance(self.screen, RequestEditor):
            self.query_one("#scenario", Select).value = (self.index + 1) % len(SCENARIOS)

    def action_previous(self):
        if not self.session.running and not isinstance(self.screen, RequestEditor):
            self.query_one("#scenario", Select).value = (self.index - 1) % len(SCENARIOS)

    def action_edit(self):
        if self.session.running or isinstance(self.screen, RequestEditor):
            return
        self.push_screen(RequestEditor(self.scenario.request), self.apply_custom)

    def apply_custom(self, request):
        if request is not None:
            self.scenario = Scenario("Custom", request)
            self.query_one("#scenario", Select).value = -1
            self.session.results.clear()
            self.session.states = dict.fromkeys(self.session.routers, "idle")
            self.refresh_request()
            self.refresh_results()

    def action_inspect(self):
        if not isinstance(self.screen, RequestEditor):
            self.query_one("#views", TabbedContent).active = "inspector"

    def action_run_compare(self):
        if self.session.running or isinstance(self.screen, RequestEditor):
            return
        # Disable synchronously, before the worker gets its first event-loop turn.
        self.set_busy(True)
        self.run_comparison()

    def set_busy(self, busy):
        for selector in ("#scenario", "#run", "#edit"):
            self.query_one(selector).disabled = busy

    @work(exclusive=True)
    async def run_comparison(self):
        try:
            async for event in self.session.run(self.scenario.request, None if self.scenario.label == "Custom" else self.index):
                self.refresh_results()
                self.query_one("#status", Static).update("Routing… inspect completed results while the other model runs." if event["type"] != "finished" else "Comparison complete. Open HTTP inspector [o] for request / response bodies.")
        finally:
            self.set_busy(False)

    async def on_unmount(self):
        if self.owns_client:
            await self.client.aclose()
