import json

from rich.console import Console, Group
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from jev_router_demo.metrics import RouterMetrics
from jev_router_demo.models import RoutingResult
from jev_router_demo.scenarios import SCENARIOS, Scenario


COMMANDS = "[r] Run  [n] Next  [p] Previous  [e] Custom  [v] View request  [o] Raw outputs  [q] Quit"


def literal_text(value: str, style: str = "") -> Text:
    """Keep malformed Unicode inspectable without changing stored measurements."""
    return Text(value.encode("utf-8", errors="backslashreplace").decode("utf-8"), style=style)


def number(value: int | float | None, suffix: str = "") -> str:
    if value is None:
        return "-"
    return f"{value:,.2f}{suffix}" if isinstance(value, float) else f"{value:,}{suffix}"


def route_line(result: RoutingResult) -> str:
    if result.decision is None:
        return "No route available"
    decision = result.decision
    web = "WEB ENABLED" if decision.needs_web else "WEB DISABLED"
    action = "HUMAN APPROVAL REQUIRED" if decision.needs_approval else "EXECUTE (SIMULATED)"
    return f"{decision.model_tier.upper()} MODEL ──► {web} ──► {action}"


def result_panel(result: RoutingResult) -> Panel:
    table = Table.grid(padding=(0, 2))
    table.add_column(style="dim")
    table.add_column()
    decision = result.decision
    table.add_row("Model", decision.model_tier.upper() if decision else "-")
    table.add_row("Web", ("YES" if decision.needs_web else "NO") if decision else "-")
    approval = Text("YES · REQUIRED", style="bold yellow") if decision and decision.needs_approval else Text("NO" if decision else "-")
    table.add_row("Approval", approval)
    table.add_row("", "")
    table.add_row("Latency", number(result.latency_ms, " ms"))
    table.add_row("Input tokens", number(result.input_tokens))
    table.add_row("Output tokens", number(result.output_tokens))
    table.add_row("Total tokens", number(result.total_tokens))
    table.add_row("Generated bytes", number(result.generated_bytes))
    table.add_row("Decision output", Text(result.output_kind))
    parsed = "Not required" if not result.parse_required else {True: "OK", False: "FAILED", None: "-"}[result.parse_success]
    table.add_row("Parse", parsed)
    table.add_row("Parse time", number(result.parse_ms, " ms"))
    items = [table, Text("\n" + route_line(result), style="bold cyan")]
    if result.error:
        items.append(literal_text("\nERROR: " + result.error, style="bold red"))
    if result.probabilities:
        items.append(Text("\nReported candidate probabilities", style="bold"))
        for field, candidates in result.probabilities.items():
            items.append(Text(field))
            for candidate, probability in candidates.items():
                bar = "█" * round(probability * 20)
                items.append(Text(f"{candidate:<10} {bar:<20} {probability:.0%}"))
    return Panel(Group(*items), title=f"{result.router_name} Router", border_style="cyan")


def cumulative_panel(metrics: dict[str, RouterMetrics]) -> Panel:
    table = Table(expand=True, box=None, padding=(0, 1))
    table.add_column("", style="dim")
    for name in metrics:
        table.add_column(name, justify="right")
    values = list(metrics.values())
    table.add_row("Requests", *(number(item.requests) for item in values))
    table.add_row("Successes", *(number(item.successes) for item in values))
    table.add_row("Avg latency (success)", *(number(item.average_latency_ms, " ms") for item in values))
    for key, label in [
        ("input_tokens", "Input tokens"), ("output_tokens", "Output tokens"),
        ("total_tokens", "Total tokens"), ("generated_bytes", "Generated bytes"),
    ]:
        cells = []
        for item in values:
            observed = item.observations[key]
            cell = number(item.totals[key]) if observed else "-"
            if observed and observed != item.requests:
                cell += f" ({observed}/{item.requests})"
            cells.append(cell)
        table.add_row(label, *cells)
    table.add_row("Parse failures", *(str(item.parse_failures) if item.parse_attempts else "-" for item in values))
    table.add_row("Errors", *(number(item.errors) for item in values))
    return Panel(
        Group(table, Text("Partial totals: (observed/request count). '-' = unavailable.", style="dim")),
        title="Cumulative Metrics", border_style="blue",
    )


def render_screen(
    console: Console,
    scenario: Scenario,
    index: int,
    results: tuple[RoutingResult, RoutingResult] | None,
    metrics: dict[str, RouterMetrics],
    message: str = "",
) -> None:
    if console.is_terminal:
        console.clear()
    console.print(Panel(Text("JEV AGENT ROUTER DEMO", justify="center", style="bold cyan")))
    console.print(Text("SIMULATION · routing decisions only; no downstream execution", style="dim"))
    label = f"Scenario {index + 1}/{len(SCENARIOS)}" if scenario is SCENARIOS[index] else "Custom request"
    console.print(Text(f"\n{label} · {scenario.label}", style="bold"))
    width = max(console.width - 4, 10)
    lines = Text(scenario.request).wrap(console, width)
    preview = list(lines[:4])
    if len(lines) > 4:
        preview[-1].truncate(width - 1)
        preview[-1].append("…")
    console.print(Panel(Text("\n").join(preview), title="Request", border_style="white"))
    if results:
        panels = [result_panel(result) for result in results]
        if console.width >= 100:
            columns = Table.grid(expand=True, padding=(0, 1))
            columns.add_column(ratio=1)
            columns.add_column(ratio=1)
            columns.add_row(*panels)
            console.print(columns)
        else:
            for panel in panels:
                console.print(panel)
    console.print(cumulative_panel(metrics))
    console.print(Text(COMMANDS, style="bold"))
    if message:
        console.print(Text(message, style="yellow"))


def show_raw_outputs(console: Console, results: tuple[RoutingResult, RoutingResult]) -> None:
    for result in results:
        console.print(Text(f"\n{result.router_name} generated routing output", style="bold cyan"))
        console.print(literal_text(result.generated_text if result.generated_text is not None else "-"))
        if result.thinking_text is not None:
            console.print(Text("Returned thinking content", style="bold"))
            console.print(literal_text(result.thinking_text))
        console.print(Text(f"{result.router_name} raw API response", style="dim"))
        raw = result.raw_response
        console.print(literal_text(json.dumps(raw, ensure_ascii=False, indent=2) if not isinstance(raw, str) else raw))
